### ISSUE TITLE
How to use in Fragment?How to use in a complicated layout in GridView?

### ISSUE THREAD

**Issue by angelen10** [tianzhijiexian/ActivityOptionsICS#1]

**Comment by kaleai** [comment]
You can use:
ActivityCompatICS.startActivity(getActivity(), intent, options.toBundle());
Welcome questions.

**Comment by kaleai** [comment]
Could you tell me which activity includes the complicated layout?

**Comment by angelen10** [comment]
@tianzhijiexian Well,my problems, there are two Fragment(FirstFragment and SecondFragment) in MainActivity, and there is a GridView in the FirstFragment, there are some preview pictures and titles in the GridView.When I click the GridView Item, it'll enter into OtherActivity, in this activity, there are some preview pictures and other informations.
I am sorry whether you could understand what i say?

**Comment by kaleai** [comment]
好吧，我大概知道你意思了。就是两个fragment在一个activity中，不能用start Activity的方法，第一个fragment是瀑布流，第二个是展示细节的activity对吧。我去看看代码，然后回复您。

**Comment by kaleai** [comment]
你可以通过ViewAnim类来做https://github.com/tianzhijiexian/ActivityOptionsICS/blob/master/library/src/com/kale/activityoptions/anim/ViewAnim.java

因为是在一个activity中，所以问题大大简化。你只需要知道原始图片的rect，还有最终图片的rect就行。这个类中提供了两个有效方法来实现你的要求。
方法名：startViewTweensAnim

**Comment by angelen10** [comment]
@tianzhijiexian 我是这样子的，在一个Fragment里面有一个GridView，然后这个GridView中的每一项包括了预览小图以及标题，然后我点击GridView的每一项都会跳转到一个新的Activity里面，这个Activity是用来显示有：预览大图，标题，以及其他的信息。因为现在在Fragment中GridView中的Item的   预览小图    和 新的Activity中的   预览大图  是同一张图片，我的问题就是这样子，你刚解决的是如此吗？

**Comment by kaleai** [comment]
“因为现在在Fragment中GridView中的Item的 预览小图 和 新的Activity中的 预览大图 是同一张图片”这是什么意思呢？还不是很清楚您的问题。如果还是想要跳转到一个新的activity中展示大图，用startActivity方法就好了，和demo中的两个activity跳转没啥差别。如果是在同一个activity中点击图片展现大图，用viewAnim就可以实现。如果有理解错误，还望指出。

**Comment by angelen10** [comment]
喔，是我理解错了，问题解决了，谢谢啦
ps：能不能弄一个Android Studio版本，你这个太好用了

**Comment by kaleai** [comment]
谢谢支持！studio那个东西更新太快，所以就没去做studio版本的。主要是因为我平常在eclipse上开发，所以就只弄了个eclipse的。想问下您是用的这个lib提供的什么效果呢？

**Comment by angelen10** [comment]
呵呵，我也觉得，不过现在很多的开源项目代码都是使用studio，然后不得不使用studio，不过现在eclipse也ok了，我就是直接把你的lib的代码拷贝到我的项目里面。我是使用你截图中的第二种效果的，这种效果挺像那个iPhone中相册的预览，哈哈。
